### ISSUE TITLE
Copy and Paste nodes

### ISSUE THREAD

**Issue by mathpeseg** [CedricGuillemet/Imogen#12]
I don't know if there is no implementation of copy and paste yet, but i can't copy and paste nodes.
If there isn't an implementation for that, could you make it please? it would help a lot. ^^

**Comment by CedricGuillemet** [comment]
Hi! No impl for C/C yet. I add it to the roadmap. Thanks!

**Comment by CedricGuillemet** [comment]
Done! Released in Imogen 0.7! https://github.com/CedricGuillemet/Imogen/releases
