### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by CedricGuillemet** [CedricGuillemet/Imogen#14]
Previously planed for this weekend, v0.2 is a bit delayed as I rewrote the evaluation code  multiple times this weekend. I'm more happy with it but it can still be better. I will release it monday or tuesday

**Comment by thirdknife** [comment]
@CedricGuillemet while this gets in, this will fix a lot of tasks on the board?

**Comment by CedricGuillemet** [comment]
everything in "Done" and "in progress"
