### ISSUE TITLE
.EXR input/output

### ISSUE THREAD

**Issue by CedricGuillemet** [CedricGuillemet/Imogen#27]

**Comment by unfa** [comment]
I think it migth be a good idea to replace FFmpeg with OIIO.
It's an industry-proven library: https://github.com/OpenImageIO/oiio

**Comment by CedricGuillemet** [comment]
Yes, that's something possible for the desktop version. For the web, I'd still use the stb_ like functions. Like for Python. use the libraries from the ext folder and on Linux, use package.
