### ISSUE TITLE
Parse .glsl code to generate meta datas

### ISSUE THREAD

**Issue by CedricGuillemet** [CedricGuillemet/Imogen#30]
For now, the metadatas are stored in Library. I'd like to get more freedom/reactivity and generate the metadata (basically parameters and types) from a parsing (threaded/jobified) of those .glsl

**Comment by Xyrio** [comment]
one simple way would be to support special one line comments inside the glsl file that provide that information

//#Input type1 name1
//#Input type2 name2

**Comment by CedricGuillemet** [comment]
That would work for .glsl but more difficult for Python/C. I think the best solution is to provide a metadata file per node. I don't like that but I can't think of another solution.
