### ISSUE TITLE
0.6.0 crashes immediately on start

### ISSUE THREAD

**Issue by Xyrio** [CedricGuillemet/Imogen#35]
windows 7 64bit

0.5.0 works

using gdb i found:
>(gdb) run
Starting program: ...\Imogen\imogen.exe
[New Thread 8244.0x4c8]
[New Thread 8244.0x2e04]
[New Thread 8244.0x26f8]
[New Thread 8244.0xdf4]
[New Thread 8244.0x2e8c]
warning: Fatal Python error:
warning: unable to load the file system codec
warning:
[Thread 8244.0x2e8c exited with code 3]
[Thread 8244.0x26f8 exited with code 3]
[Thread 8244.0xdf4 exited with code 3]
[Thread 8244.0x2e04 exited with code 3]
[Inferior 1 (process 8244) exited with code 03]

**Comment by CedricGuillemet** [comment]
I can reproduce it! Thanks ! I let you know when it's fixed

**Comment by CedricGuillemet** [comment]
New 0.6.1 release that should be fixed 
https://github.com/CedricGuillemet/Imogen/releases/tag/0.6.1
Let me know if you still get an issue.
Thank you Xyrio

**Comment by Xyrio** [comment]
0.6.1 works
