### ISSUE TITLE
Creating node when zoomed and pan positions it in the wrong place

### ISSUE THREAD

**Issue by mrvux** [CedricGuillemet/Imogen#47]
Hello, as per the gif here 

![imotep_issue1](https://user-images.githubusercontent.com/272494/52175942-bb3a3600-27bc-11e9-97a1-a36da98d086d.gif)

When creating the node I would hope to have it in the place I initially set right click.

Thanks

**Comment by CedricGuillemet** [comment]
Fixed in dev-0.10 branch
