### ISSUE TITLE
Creating connection between nodes, small improvement

### ISSUE THREAD

**Issue by mrvux** [CedricGuillemet/Imogen#48]
Hello, as per the screenshot here : 

![imotep_link](https://user-images.githubusercontent.com/272494/52175951-e45ac680-27bc-11e9-8869-8640ddd938fc.gif)

Dragging the connection from the transform to the transform should pick the first available connection, this makes authoring much much faster.

**Comment by CedricGuillemet** [comment]
Fixed in dev-0.9
