### ISSUE TITLE
Suggestion: function nodes

### ISSUE THREAD

**Issue by ruchitinfushion** [CedricGuillemet/Imogen#5]
node list
*absolute - return absolute value
*acos - inverse of cos
*asin - inverse of sin
*atan - inverse of tan
*angle - angle between two nodes
*ceil - return the smallest integer value that is not less than the argument
*floor - return the largest integer value that is not greater than the argument
*trunc - return the largest whole value that is not greater than the argument
*clamp - clamps to the min-max range, If number is outside the range, the return value is clamped to          min or max, otherwise.
*sqrt - square root

**Comment by CedricGuillemet** [comment]
Clamp will be available in next release
