### ISSUE TITLE
Crazy idea here

### ISSUE THREAD

**Issue by badjano** [CedricGuillemet/Imogen#7]
Would it be possible to integrate this with shadertoy? It would be ridiculously awesome

**Comment by CedricGuillemet** [comment]
Yes! It's one of the motivations behind this project. If you look at some nodes like iqnoise or the pbr one, you'll se they are coming from a Shadertoy. Integration needs some tweaks (mouse support, UV name, ...) but it's quite straightforward. You can imagine a little modeler node (add SDF volumes, unions,..) and use the result with a tone mapping node and an image writer...
I'd like to add a simple painter node, and some nodes for terrain editing (erosions, snow,...) too...well, lot of things to do :)
Did you mean generate a shadertoy from the nodegraph?

**Comment by badjano** [comment]
No! You got it! Man this thing has potential! look out Substance Designer! hehe
