### ISSUE TITLE
C Node question

### ISSUE THREAD

**Issue by brionholland** [CedricGuillemet/Imogen#79]
I've been playing around with the node editor and it is a ton of fun.  I have a question about the C nodes.  I've been trying to add more functionality to the C nodes and I am attempting to include libraries like stdio and the like, but if I add an include to any of the C node scripts I get a rotating set of errors that either say source not found, relating to the ntdll.dll or an "InProcessClient.pdb not loaded, Access violation writing location" error.  Any ideas?

Thanks!

**Comment by CedricGuillemet** [comment]
I've started with tinyC for interpreting C but totally removed it in 0.14. It was not meant to be a fully supported C with includes and library. Just a handy way of adding some scripts to some nodes.

**Comment by brionholland** [comment]
Is the main intended way to add node scripts going to be python or sticking with glsl?

**Comment by CedricGuillemet** [comment]
Python or in app compiled c++ code .

**Comment by brionholland** [comment]
Cool.  Again, I really like the way you have the system set up, it is pretty cool.  I have reverted back to the.13 version as the web system was giving me some issue.  I'm sure it was me as I'm still starting out and learning as I go along.  When it comes to using python scripts, there is one testnode script, I'm unsure how it would be referenced in the json file.  Do you have any examples of other python scripts or how it is referenced in the json.  If not, please to don't spend time on it, I'm just curious and fiddling around :)

**Comment by CedricGuillemet** [comment]
No, sorry. The Python stuff is still experimental and rather limited.

**Comment by brionholland** [comment]
Ahhh, okay, then I will feel a bit better about myself for not getting it to function :). In what files are you placing the scripting for the compiled C++ code for the nodes?

**Comment by CedricGuillemet** [comment]
It's done here, for example for imageWrite : https://github.com/CedricGuillemet/Imogen/blob/dev-0.14/src/Nodes/ImageWrite.h
Check whole folder to other nodes.

**Comment by brionholland** [comment]
Awesome,  thanks for taking the time to answer my questions!  Hope you have a great day!
